### ISSUE TITLE
Game crash on client side

### ISSUE THREAD

**Issue by bagruj111** [JerichoFletcher/mechanical-warfare#129]
I play Mechanical Warfare v1.6.2 with friends, Im server. Im running but friends have game crashes, only them.
we try 1.6.1 and same game crash

### **Crash 1**
org.mozilla.javascript.EcmaError: TypeError: Cannot call method "getX" of null (scrapper#16)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4256)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4234)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4267)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4286)
	at org.mozilla.javascript.ScriptRuntime.undefCallError(ScriptRuntime.java:4303)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2569)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2562)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:96)
	at org.mozilla.javascript.gen.scrapper_33._c_anonymous_3(scrapper:16)
	at org.mozilla.javascript.gen.scrapper_33.call(scrapper)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:409)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3566)
	at org.mozilla.javascript.gen.scrapper_33.call(scrapper)
	at org.mozilla.javascript.JavaAdapter.doCall(JavaAdapter.java:613)
	at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:594)
	at adapter43.init(<adapter>)
	at mindustry.entities.type.Bullet.added(Bullet.java:285)
	at mindustry.entities.EntityGroup.updateEvents(EntityGroup.java:118)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:44)
	at mindustry.core.Logic.update(Logic.java:240)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:138)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)

### **Crash 2**
java.lang.RuntimeException: Failed to to read remote method 'onEntitySnapshot'!
	at mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:146)
	at mindustry.core.NetClient.lambda$new$4(NetClient.java:134)
	at mindustry.net.Net.handleClientReceived(Net.java:247)
	at mindustry.desktop.steam.SNet$1.update(SNet.java:83)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)
Caused by: java.lang.RuntimeException: java.io.EOFException
	at mindustry.core.NetClient.onEntitySnapshot(NetClient.java:407)
	at mindustry.gen.RemoteReadClient.readPacket(RemoteReadClient.java:144)
	... 7 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at java.io.DataInputStream.readFloat(DataInputStream.java:446)
	at mindustry.entities.units.Statuses.readSave(Statuses.java:143)
	at mindustry.entities.type.Unit.readSave(Unit.java:155)
	at mindustry.entities.type.BaseUnit.read(BaseUnit.java:403)
	at mindustry.entities.type.base.BuilderDrone.read(BuilderDrone.java:236)
	at mindustry.core.NetClient.onEntitySnapshot(NetClient.java:391)
	... 8 more

**Comment by GlennFolker** [comment]
Provide a way on how you recreate that issue. I'm guessing, you deploy a bunch of scrappers into the enemy base?

**Comment by GglLfr** [comment]
Okay, Crash 1 should be fixed. Now, would you mind telling me how you reproduced Crash 2?

**Comment by bagruj111** [comment]
I used Mechanical Warfare map frozen-valley.msav Edit version
[map_50.zip](https://github.com/JerichoFletcher/mechanical-warfare/files/5621849/map_50.zip)

Crash 1 org.mozilla.javascript.EcmaError: TypeError: Cannot call method "getX" of null (scrapper#16)
happens when the Scrapper touches the wall. every time

Crash 2: When we had an hour to play, Crush2 started to be made as soon as the players log in, it kick them out. And Im server and my game running ok. only friends are kicked out

**Comment by bagruj111** [comment]
[117.zip](https://github.com/JerichoFletcher/mechanical-warfare/files/5621917/117.zip)
I have game save when Crash 2 started

**Comment by ghost** [comment]
~~Are you sure your friend's mechanical-warfare is in the same version as you?~~

Your friend's client cannot read your "save" of the unit.

**Comment by bagruj111** [comment]
We have same version. After this crushes we try Mechanical Warfare v1.6.1 version and result was same Crash 2 happen

**Comment by GglLfr** [comment]
Have you tried using the _newest_? The one where you just directly download it from GitHub
