### ISSUE TITLE
Can't place Serpent Factory

### ISSUE THREAD

**Issue by dsethlewis** [JerichoFletcher/mechanical-warfare#62]
My game crashes whenever I try to place a Serpent Factory block. I'm using the latest version of the mod, which I just reinstalled today.

Here's the error message I get in the crash report:

java.lang.NullPointerException
	at arc.graphics.g2d.Draw.rect(Draw.java:199)
	at mindustry.world.blocks.BuildBlock.drawLayer(BuildBlock.java:196)
	at mindustry.graphics.BlockRenderer.drawBlocks(BlockRenderer.java:284)
	at mindustry.core.Renderer.draw(Renderer.java:254)
	at mindustry.core.Renderer.update(Renderer.java:141)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:138)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:158)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:146)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:46)

There appears to be an issue with drawing the block. I noticed that the Serpent Factory is unique in the mod in having a single sprite with just a clear top. I couldn't figure out how to fix the problem, though. And it's certainly possible that I'm doing something wrong, since the rest of the mod seems to work perfectly.

I'd love to have a fix because the serpents sound dope, but for now I'm just going to take the factory out of the package so I don't try to place it by accident.

**Comment by JerichoFletcher** [comment]
See if it's resolved by now. Thanks👍
